CREATE TABLE PROJETO (
	IDPROJETO SERIAL PRIMARY KEY,
	TITULO VARCHAR(200),
	DESCRICAO VARCHAR(2000)
);

CREATE TABLE USUARIO (
	IDUSUARIO SERIAL PRIMARY KEY,
	NOME VARCHAR(200),
	SENHA VARCHAR(50),
	NOMEUSUARIO VARCHAR(50),
	EMAIL VARCHAR(200) UNIQUE
);

CREATE TABLE PROJETO_USUARIO (
	IDPROJETO INTEGER,
	IDUSUARIO INTEGER,
	TIPOACESSO INTEGER,
	PRIMARY KEY (IDPROJETO, IDUSUARIO),
	CONSTRAINT FK_PROJUSU_PROJETO_ID FOREIGN KEY (IDPROJETO) REFERENCES PROJETO(IDPROJETO),
	CONSTRAINT FK_PROJUSU_USUARIO_ID FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO)
);

INSERT INTO TABELAS(NOME, COLUNAS, DESCRICAO) VALUES
('PROJETO','IDPROJETO, TITULO, DESCRICAO', 'TABELA DE PROJETOS'),
('USUARIO','IDUSUARIO, NOME, SENHA, NOMEUSUARIO, EMAIL', 'TABELA DE USUARIOS'),
('PROJETO_USUARIO','IDPROJETO, IDUSUARIO, TIPOACESSO', 'TABELA QUE RELACIONA PROJETOS COM USUARIOS');